config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :searches, only: :index

  resources :lessons, only: [:index, :show], param: :slug do
    resources :submissions, only: [:index, :create]
    resources :ratings, only: [:create, :update]
  end

  resources :submissions, only: [:show, :update] do
    resources :comments, only: [:create]
  end

  resources :assignments, only: [:show]

  resources :announcements, only: [:show, :destroy]

  resources :announcement_receipts, only: [:create]

  resources :users, only: [:index, :show], param: :username

  resources :teams, only: [:index, :show] do
    resources :assignments, only: [:index, :create]
    resources :announcements, only: [:index, :create]
  end
  resources :question_queues, only: [:create, :update]

  resources :questions do
    resources :answers, only: [:edit, :update, :create, :destroy]
    resources :question_comments, only: [:create, :destroy]
  end

  resources :answers, only: [] do
    resources :answer_comments, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy] do
    get "failure", on: :member
  end

  resource :dashboard, only: [:show]

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"

  get "/start", to: "static_pages#start"
  get "/dailies", to: "static_pages#dailies"
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  belongs_to :question_queue
  belongs_to :accepted_answer, class_name: "Answer"
  has_many :answers, dependent: :destroy
  has_many :question_comments, dependent: :destroy

  validates :title, presence: true, length: { in: 10..200 }
  validates :body, presence: true, length: { in: 15..10000 }
  validates :user, presence: true

  validate :accepted_answer_belongs_to_question

  scope :queued, ->() {
    joins(:question_queue).
      where("questions.question_queue_id IS NOT NULL AND \
        question_queues.status NOT LIKE '%done%'")
  }

  def accepted_answer_belongs_to_question
    if accepted_answer && !answers.include?(accepted_answer)
      errors.add(:accepted_answer_id, "must belong to this question")
    end
  end

  def sorted_answers
    answers.sort_by { |answer| answer.accepted? ? 0 : 1 }
  end

  def self.unanswered
    where(answers_count: 0)
  end

  def queue
    question_queue.present? ? reset_question_queue : create_question_queue
  end

  def self.search(query)
    where("searchable @@ plainto_tsquery(?)", query)
  end

  private

  def reset_question_queue
    question_queue.update_attributes(status: 'open', no_show_counter: 0)
  end

  def create_question_queue
    update_attributes(question_queue: QuestionQueue.create)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    if params[:query] == "unanswered"
      @questions = Question.unanswered
      @filter = "unanswered"
    elsif params[:query] == "queued"
      @questions = Question.queued.sort_by { |q| q.question_queue.sort_order }
      @filter = "queued"
    else
      @questions = Question.order(created_at: :desc)
      @filter = "newest"
    end
    @questions = QuestionDecorator.decorate_collection(@questions)
  end

  def show
    @question = Question.find(params[:id]).decorate
    @answer = Answer.new
    @question_comment = QuestionComment.new
    @question_comments = @question.question_comments.limit(30)
    @answer_comment = AnswerComment.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(create_params)
    @question.user = current_user
    @question.save

    if @question.save
      flash[:info] = "Question saved."
      redirect_to question_path(@question)
    else
      flash[:alert] = "Failed to save question."
      render :new
    end
  end

  def update
    question = current_user.questions.find(params[:id])
    question.update(update_params)
    redirect_to question_path(question), info: "Your question has been updated."
  end

  def destroy
    @question = current_user.questions.find(params[:id])
    @question.destroy
    redirect_to questions_path, info: "Successfully deleted question"
  end

  def edit
    @question = Question.find(params[:id])
  end

  private

  def create_params
    params.require(:question).permit(:title, :body)
  end

  def update_params
    params.require(:question).permit(:accepted_answer_id, :title, :body)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def questions_header(filter)
    if filter == "newest"
      "Newest Questions"
    elsif filter == "unanswered"
      "Unanswered Questions"
    end
  end
end

app/views/questions/_markdown.html.erb
<%-

items = [
  "*italics*",
  "**bold**",
  "[link](http://launchacademy.com)",
  "* item 1\n* item 2\n* item 3",
  "```ruby\nrequire 'pry'\n```"
]

%>

<table class="table--bordered">
  <tr>
    <th>syntax</th>
    <th>rendered as</th>
  </tr>

  <%- items.each do |item| %>
    <tr>
      <td><p><%= item.gsub("\n", "<br/>").html_safe %>
      <td><%= render_safe_markdown(item) %>
    </tr>
  <% end %>
</table>

app/views/questions/edit.html.haml
- content_for(:title) do
  Edit Question - Launch Academy

%ul.breadcrumbs
  %li= link_to "Questions", questions_path
  %li.current= link_to "Edit Question", edit_question_path(@question)

%h2 Edit Question

#edit-question
  = form_for @question do |f|
    = field_set_tag "Edit Question" do

      = f.label :title, "Title"
      = f.text_field :title

      = f.label :body, "Body"
      = f.text_area :body

      = f.submit "Update Question", class: "button"

app/views/questions/index.html.haml
- content_for(:title) do
  Questions - Launch Academy

%ul.breadcrumbs
  %li.current= link_to "Questions", questions_path

#new-question
  = link_to new_question_path, class: "button success" do
    %i.fi-plus
    Ask A Question


%dl.sub-nav
  %dt Filter:
  %dd{ class: ("active" if @filter == "newest") }= link_to "Newest", questions_path
  %dd{ class: ("active" if @filter == "unanswered") }= link_to "Unanswered", questions_path(query: "unanswered")
  %dd{ class: ("active" if @filter == "queued") }= link_to "Question Queue", questions_path(query: "queued")

%h2= questions_header(@filter)

.questions
  - @questions.each_with_index do |question, index|
    - if question.in_queue?
      .question-queue{id: question.queue_id}
        %div.row
          %div.large-2.columns
            %div{ class: question.queue_progress }= index + 1
            %p
          %div.large-10.columns
            %h3= question.user.name
            = link_to question.title, question_path(question)
            - if question.in_progress?
              %h5.assignee= question.assignee
            %div.queue-buttons
              - if question.admin_access?
                = question_queue_update_button(question.question_queue)
                - if question.open?
                  = link_to "No Show", question_queue_path(id: question.question_queue, question_queue: { status: "no-show"}), method: :patch, class: "ee-button no-show"
    - elsif @filter != 'queued'
      .question.box
        %span
          %h3.title
            = link_to question.title, question
            = question.queue_status
        %p.answer_count= pluralize question.answers_count, "answer"

app/views/questions/new.html.haml
- content_for(:title) do
  Ask New Question - Launch Academy

%ul.breadcrumbs
  %li= link_to "Questions", questions_path
  %li.current= link_to "New Question", new_question_path

%h2 Ask Question

#new-question
  = form_for @question do |f|
    = field_set_tag "Ask Question" do

      = f.label :title, "Title"
      = f.text_field :title

      = f.label :body, "Body"
      = f.text_area :body, rows: 15

      = f.submit "Ask Question", class: "button"


%p
  Questions support markdown.  For more information on Markdown syntax, click <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet">here</a>.

= render 'markdown'

app/views/questions/show.html.haml
- content_for(:title) do
  = "#{@question.title} - Launch Academy"

%ul.breadcrumbs
  %li= link_to "Questions", questions_path
  %li.current= link_to @question.title, question_path(@question)

#question
  %h2.title
    = @question.title
    = @question.queue_status
  %hr
  .row
    .small-8.columns
      %p.body~ render_safe_markdown(@question.body)
      %ul.question-comments
        - @question_comments.each do |comment|
          %li.qa-comment
            = comment.body
            %span.comment-user
              = " - #{comment.user.name}, #{comment_time(comment.created_at)} "
            - if comment.user == current_user
              = link_to question_question_comment_path(@question, comment),
                method: :delete,
                class: 'delete-question-comment',
                data: { confirm: "Are you sure you want to delete comment?" } do
                %i.fi-x.delete-comment

      %p.add-question-comment= link_to "add comment"
      #question-comment.hidden
        = form_for [@question, @question_comment] do |f|
          = f.text_area :body

          = f.submit "create comment", class: "button tiny success", id: "create-question-comment"

    .small-4.columns
      .user
        = link_to @question.user.username, user_path(@question.user)
        asked on
        .created_at= format_datetime(@question.created_at)
        - if @question.user == current_user
          = link_to "Edit Question", edit_question_path(@question)
          %br
          = link_to "Delete question", question_path(@question), method: :delete

#answers
  %h3.answer-count= pluralize(@question.answers.count, "answer")

  - @question.sorted_answers.each do |answer|
    - if answer.persisted?
      .row.answer{ class: @question.accepted_answer_id == answer.id ? 'accepted-answer' : ''  }
        .small-8.columns
          %p.body~ render_safe_markdown(answer.body)
          - if answer.user == current_user
            = link_to "Edit Answer", edit_question_answer_path(@question, answer), class: "button tiny success"
            = link_to "Delete Answer", question_answer_path(@question, answer), method: :delete, class: "button tiny alert"

          %ul.answer-comments
            - if answer.answer_comments.present?
              - answer.answer_comments.each do |comment|
                %li.qa-comment
                  = comment.body
                  %span.comment-user
                    = " - #{comment.user.name}, #{comment_time(comment.created_at)}"
                  - if comment.user == current_user
                    = link_to answer_answer_comment_path(answer, comment),
                      method: :delete,
                      class: 'delete-answer-comment',
                      data: { confirm: "Are you sure you want to delete comment?" } do
                      %i.fi-x.delete-comment

          %p.add-answer-comment= link_to "add comment"
          .answer-comment.hidden
            = form_for [answer, @answer_comment] do |f|
              = f.text_area :body

              = f.submit "create comment", class: "button tiny success", id: 'create-answer-comment'

        .small-4.columns
          .user
            = link_to answer.user.username, user_path(answer.user)
            answered on
            .answered_at= format_datetime(answer.created_at)
          - if @question.accepted_answer_owned_by_current_user?(answer)
            .accepted
              %i.fi-check.large
              accepted answer
              = form_for @question do |f|
                = f.hidden_field :accepted_answer_id, value: nil
                = f.submit "Unaccept answer", class: "tiny button", id: "unaccept-answer"
          - elsif @question.user == current_user
            .accept-form
              = form_for @question do |f|
                = f.hidden_field :accepted_answer_id, value: answer.id
                = f.submit "Accept Answer", class: "tiny button"

#new-answer
  = form_for [@question, @answer] do |f|
    = field_set_tag "Answer Question" do

      = f.label :body, "Answer"
      = f.text_area :body, rows: 10

      = f.submit "Submit Answer", class: "button"
      - if current_user.try(:role) == 'admin'
        = link_to "Let's Talk!", question_queues_path(question_id: @question), method: :post, class: "button alert"