config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :searches, only: :index

  resources :lessons, only: [:index, :show], param: :slug do
    resources :submissions, only: [:index, :create]
    resources :ratings, only: [:create, :update]
  end

  resources :submissions, only: [:show, :update] do
    resources :comments, only: [:create]
  end

  resources :assignments, only: [:show]

  resources :announcements, only: [:show, :destroy]

  resources :announcement_receipts, only: [:create]

  resources :users, only: [:index, :show], param: :username

  resources :teams, only: [:index, :show] do
    resources :assignments, only: [:index, :create]
    resources :announcements, only: [:index, :create]
  end
  resources :question_queues, only: [:create, :update]

  resources :questions do
    resources :answers, only: [:edit, :update, :create, :destroy]
    resources :question_comments, only: [:create, :destroy]
  end

  resources :answers, only: [] do
    resources :answer_comments, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy] do
    get "failure", on: :member
  end

  resource :dashboard, only: [:show]

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"

  get "/start", to: "static_pages#start"
  get "/dailies", to: "static_pages#dailies"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :submissions, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :team_memberships, dependent: :destroy
  has_many :teams, through: :team_memberships
  has_many :assignments, through: :teams
  has_many :announcements, through: :teams
  has_many :assigned_lessons, through: :assignments, source: :lesson
  has_many :answers, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :announcement_receipts, dependent: :destroy
  has_many :question_queues, dependent: :destroy
  has_many :question_comments, dependent: :destroy
  has_many :answer_comments, dependent: :destroy

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :uid, presence: true, uniqueness: { scope: :provider }
  validates :provider, presence: true
  validates :token, presence: true
  validates :role, presence: true, inclusion: { in: ["member", "admin"] }

  before_validation :ensure_authentication_token

  def to_param
    username
  end

  def self.find_or_create_from_omniauth(auth)
    account_keys = { uid: auth["uid"], provider: auth["provider"] }

    user = User.find_or_initialize_by(account_keys)
    user.email = auth["info"]["email"]
    user.username = auth["info"]["nickname"]
    user.name = auth["info"]["name"]
    user.save!
    user
  end

  def ensure_authentication_token
    if token.blank?
      self.token = SecureRandom.urlsafe_base64
    end
  end

  def admin?
    role == "admin"
  end

  def has_completed_lesson?(lesson)
    lesson.submissions.has_submission_from?(self)
  end

  def belongs_to_org?(organization, oauth_token)
    if organization.nil? || organization.empty?
      true
    else
      github_orgs(oauth_token).any? { |org| org["login"] == organization }
    end
  end

  def calendars
    result = []
    teams.each do |team|
      result << team.calendar if team.calendar
    end
    result.uniq
  end

  def latest_announcements(count)
    announcements.
      joins("LEFT JOIN announcement_receipts ON announcements.id = \
        announcement_receipts.announcement_id AND \
        announcement_receipts.user_id = #{id}").
      where("announcement_receipts.id IS NULL").
      order(created_at: :desc).limit(count)
  end

  def core_assignments
    assignments.where(required: true).order(due_on: :asc)
  end

  def non_core_assignments
    assignments.where(required: false).order(due_on: :asc)
  end

  private

  def github_orgs(token)
    JSON.parse(Net::HTTP.get(github_orgs_url(token)))
  end

  def github_orgs_url(token)
    URI("https://api.github.com/users/#{username}/orgs?access_token=#{token}")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find_by!(username: params[:username])
    @count = Comment.where(user_id: @user.id).count
  end
end

app/views/users/index.html.haml
- content_for(:title) do
  Users - Launch Academy

%ul.breadcrumbs
  %li.current= link_to "Users", users_path

%h2 Users

%ul.block
  - @users.each do |user|
    %li= link_to user.username, user_path(user)

app/views/users/show.html.haml
- content_for(:title) do
  = "#{@user.username} - Launch Academy"

%ul.breadcrumbs
  %li= link_to "Users", users_path
  %li.current= link_to @user.username, user_path(@user)

- if !@user.name.blank?
  %h2= "User: #{@user.username} (#{@user.name})"
- else
  %h2= "User: #{@user.username}"

%h3= "#{@user.username}\'s comments: #{@count}"

- if @user == current_user
  #settings
    .box
      .box__header
        %h3 Account Settings

      .box__body
        .row
          .small-3.columns
            = label_tag :token, "Token", class: "right inline"
          .small-9.columns
            %span.token-field
              Hidden from view
            %span.hidden.token-field
              = text_field_tag :token, @user.token, readonly: true
            %a#show-token Toggle

#teams
  .box
    .box__header
      %h3 Teams

    .box__body
      %ul.block
        - @user.teams.each do |team|
          %li= link_to team.name, team_path(team)

#submissions
  .box
    .box__header
      %h3 Submissions

    .box__body
      %table.tablesorter
        %thead
          %tr
            %th Lesson
            %th Submitted On
            %th Number Of Comments

        %tbody
          - @user.submissions.each do |submission|
            %tr
              %td= link_to submission.lesson.title, submission_path(submission)
              %td= format_datetime(submission.created_at)
              %td= submission.comments.count