config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :searches, only: :index

  resources :lessons, only: [:index, :show], param: :slug do
    resources :submissions, only: [:index, :create]
    resources :ratings, only: [:create, :update]
  end

  resources :submissions, only: [:show, :update] do
    resources :comments, only: [:create]
  end

  resources :assignments, only: [:show]

  resources :announcements, only: [:show, :destroy]

  resources :announcement_receipts, only: [:create]

  resources :users, only: [:index, :show], param: :username

  resources :teams, only: [:index, :show] do
    resources :assignments, only: [:index, :create]
    resources :announcements, only: [:index, :create]
  end
  resources :question_queues, only: [:create, :update]

  resources :questions do
    resources :answers, only: [:edit, :update, :create, :destroy]
    resources :question_comments, only: [:create, :destroy]
  end

  resources :answers, only: [] do
    resources :answer_comments, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy] do
    get "failure", on: :member
  end

  resource :dashboard, only: [:show]

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"

  get "/start", to: "static_pages#start"
  get "/dailies", to: "static_pages#dailies"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  has_many :answer_comments, dependent: :destroy
  belongs_to :user
  belongs_to :question, counter_cache: true

  validates :user, presence: true
  validates :question, presence: true
  validates :body, presence: true, length: { in: 10..10000 }

  def accepted?
    question.accepted_answer == self
  end

  def self.search(query)
    where("searchable @@ plainto_tsquery(?)", query)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  def create
    @question = Question.find(params[:question_id]).decorate
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user

    if @answer.save
      flash[:info] = "Answer saved."
      redirect_to question_path(@question)
    else
      flash[:alert] = "Failed to save answer."
      redirect_to question_path(@question)
    end
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def update
    answer = current_user.answers.find(params[:id])
    answer.update(answer_params)
    redirect_to question_path(answer.question),
      info: "Your answer has been updated."
  end

  def destroy
    answer = current_user.answers.find(params[:id])
    answer.destroy
    redirect_to question_path(answer.question),
      info: "Your answer has been deleted."
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/edit.html.haml
- content_for(:title) do
  = "Edit Answer - Launch Academy"

%ul.breadcrumbs
  %li= link_to "Questions", questions_path
  %li= link_to @question.title, question_path(@question)
  %li.current Edit Answer

#question
  %h2.title= @question.title
  = link_to "Edit Question", edit_question_path(@question)
  .row
    .small-8.columns
      %p.body= @question.body
    .small-4.columns
      .user
        = link_to @question.user.username, user_path(@question.user)
        asked on
        .created_at= format_datetime(@question.created_at)

#edit-answer
  = form_for [@question, @answer] do |f|
    = field_set_tag "Edit Answer" do

      = f.label :body, "Answer"
      = f.text_area :body

      = f.submit "Update Answer", class: "button"