config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :searches, only: :index

  resources :lessons, only: [:index, :show], param: :slug do
    resources :submissions, only: [:index, :create]
    resources :ratings, only: [:create, :update]
  end

  resources :submissions, only: [:show, :update] do
    resources :comments, only: [:create]
  end

  resources :assignments, only: [:show]

  resources :announcements, only: [:show, :destroy]

  resources :announcement_receipts, only: [:create]

  resources :users, only: [:index, :show], param: :username

  resources :teams, only: [:index, :show] do
    resources :assignments, only: [:index, :create]
    resources :announcements, only: [:index, :create]
  end
  resources :question_queues, only: [:create, :update]

  resources :questions do
    resources :answers, only: [:edit, :update, :create, :destroy]
    resources :question_comments, only: [:create, :destroy]
  end

  resources :answers, only: [] do
    resources :answer_comments, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy] do
    get "failure", on: :member
  end

  resource :dashboard, only: [:show]

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"

  get "/start", to: "static_pages#start"
  get "/dailies", to: "static_pages#dailies"
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  SUBMITTABLE_TYPES = ["challenge", "exercise"]

  self.inheritance_column = :_type_disabled

  has_many :submissions, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :assignments, dependent: :destroy

  validates :title, presence: true
  validates :slug, presence: true, uniqueness: true
  validates :body, presence: true
  validates :type, presence: true, inclusion: [
    "article", "tutorial", "challenge", "exercise"
  ]

  validates :position, presence: true, numericality: {
    greater_than_or_equal_to: 1
  }

  validates :visibility, presence: true, inclusion: [
    "public", "assign"
  ]

  mount_uploader :archive, LessonUploader

  def to_param
    slug
  end

  def submissions_viewable_by(user)
    if user.admin?
      submissions
    else
      if submissions.has_submission_from?(user)
        submissions.where("user_id = ? OR public = true", user.id)
      else
        submissions.none
      end
    end
  end

  def accepts_submissions?
    SUBMITTABLE_TYPES.include?(type)
  end

  def self.public
    where(visibility: "public")
  end

  def self.visible_for(user)
    where("visibility = 'public' OR id IN (?)", user.assigned_lesson_ids)
  end

  def self.submittable
    where(type: SUBMITTABLE_TYPES)
  end

  def self.challenges
    type("challenge")
  end

  def self.search(query)
    where("searchable @@ plainto_tsquery(?)", query)
  end

  def self.type(type)
    where(type: type)
  end

  def self.import_all!(lessons_dir)
    lessons = {}
    dependencies = {}

    Dir.entries(lessons_dir).each do |filename|
      path = File.join(lessons_dir, filename)

      if File.directory?(path) && !filename.start_with?(".")
        lesson, lesson_dependencies = import(path)
        lessons.merge!(lesson.slug => lesson)
        dependencies.merge!(lesson_dependencies)
      end
    end

    order_lessons(dependencies).each_with_index do |slug, position|
      lesson = lessons[slug]
      lesson.position = position + 1
      lesson.save!
    end
  end

  def self.import(source_dir)
    slug = File.basename(source_dir)

    attributes = YAML.load_file(File.join(source_dir, ".lesson.yml"))
    content = File.read(File.join(source_dir, "#{slug}.md"))

    lesson = Lesson.find_or_initialize_by(slug: slug)
    lesson.body = content
    lesson.title = attributes["title"]
    lesson.description = attributes["description"]
    lesson.type = attributes["type"]
    lesson.position = attributes["position"]
    lesson.visibility = attributes["visibility"] || "public"

    if lesson.accepts_submissions?
      Dir.mktmpdir("archive") do |tmpdir|
        parent_dir = File.dirname(source_dir)
        archive_path = File.join(tmpdir, "#{slug}.tar.gz")
        system("tar", "zcf", archive_path, "-C", parent_dir, slug)
        lesson.archive = File.open(archive_path)
      end
    end

    if attributes["depends"]
      dependencies = attributes["depends"].split(",").map(&:strip)
    else
      dependencies = []
    end

    [lesson, { lesson.slug => dependencies }]
  end

  def self.order_lessons(lesson_prereqs)
    # This method uses the topological sort algorithm to produce a
    # linear ordering of lessons given their dependencies.  The
    # lessons_prereqs param is a hash where the key is the lesson slug
    # and the value is an array of dependencies:
    #
    # lesson_prereqs = { "foo" => ["bar"], "bar" => ["baz"], "baz" => [] }

    ordered = []
    next_lessons = []

    lesson_prereqs.each do |lesson, prereqs|
      if prereqs.empty?
        next_lessons.push(lesson)
      end
    end

    next_lessons.sort!

    while !next_lessons.empty?
      next_lesson = next_lessons.shift
      ordered.push(next_lesson)

      lesson_prereqs.each do |lesson, prereqs|
        if prereqs.include?(next_lesson)
          prereqs.delete(next_lesson)

          if prereqs.empty?
            next_lessons.push(lesson)
          end
        end
      end
    end

    ordered
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lessons = filter_lessons(Lesson.order(:position))
  end

  def show
    @lesson = Lesson.find_by!(slug: params[:slug])
    @rating = @lesson.ratings.find_or_initialize_by(user: current_user)
  end

  private

  def filter_lessons(lessons)
    lessons = visible_filter(current_user, lessons)
    lessons = type_filter(params[:type], lessons)
    lessons = submittable_filter(params[:submittable], lessons)
    lessons
  end

  def submittable_filter(flag, lessons)
    if flag == "1"
      lessons.submittable
    else
      lessons
    end
  end

  def type_filter(type, lessons)
    if type
      lessons.type(type)
    else
      lessons
    end
  end

  def visible_filter(user, lessons)
    if user
      lessons.visible_for(user)
    else
      lessons.public
    end
  end
end

app/views/lessons/index.html.haml
- content_for(:title) do
  Lessons - Launch Academy

%ul.breadcrumbs
  %li.current= link_to "Lessons", lessons_path

%h2 Lessons

- if params[:query]
  .result-count
    - if @lessons.empty?
      = "No results found for \"#{params[:query]}\"."
    - else
      = "Found #{@lessons.length} result(s) for \"#{params[:query]}\"."

.lessons
  - @lessons.each do |lesson|
    .lesson
      .lesson-type{ class: lesson.type }= lesson.type
      %h3.title= link_to lesson.title, lesson
      .clarity= "Clarity Score: #{lesson.clarity.round(1)}"
      .helpfulness= "Helpfulness Score: #{lesson.helpfulness.round(1)}"
      .review_count= "Reviews: #{lesson.ratings.count}"
      .description
        = lesson.description

app/views/lessons/show.html.haml
- content_for(:title) do
  = "#{@lesson.title} - Launch Academy"

%ul.breadcrumbs
  %li= link_to "Lessons", lessons_path
  %li.current= link_to @lesson.title, lesson_path(@lesson)
  - if @lesson.accepts_submissions?
    %li= link_to "Submissions", lesson_submissions_path(@lesson)

.lesson-type{ class: @lesson.type }= @lesson.type

%h2.lesson-title= @lesson.title

#body
  ~ render_markdown(@lesson.body)

- if user_signed_in?
  #rating
    = form_for [@lesson, @rating] do |f|
      = field_set_tag "Rate this lesson" do
        #helpfulness
          = f.label :helpfulness, "How useful was the material discussed?"
          - (1..5).each do |rating|
            = f.label "helpfulness_#{rating}", class: "inline" do
              = rating
              = f.radio_button :helpfulness, rating

        #clarity
          = f.label :clarity, "How clearly explained were the concepts?"
          - (1..5).each do |rating|
            = f.label "clarity_#{rating}", class: "inline" do
              = rating
              = f.radio_button :clarity, rating

        #comment
          = f.label :comment, "Additional comments (optional)"
          = f.text_area :comment, rows: 5

        = f.submit "Rate Lesson", class: "button"